import logging
import os
import time
from typing import Dict, Any, List

from fastapi import FastAPI, Request, HTTPException, Security, Depends
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from pydantic import ValidationError

from models import (
    EnterpriseMetadata, RawPacketMetadata, FlowMetadata, 
    TLSFingerprintEvent, AlertEvent, IngestionRequest
)
from kafka_producer import kafka_service

# Logging setup for JSON (useful for Kibana/Datadog ingestion)
from pythonjsonlogger import jsonlogger
logger = logging.getLogger("nf-ingestion")
logHandler = logging.StreamHandler()
formatter = jsonlogger.JsonFormatter('%(asctime)s %(levelname)s %(name)s %(message)s')
logHandler.setFormatter(formatter)
logger.addHandler(logHandler)
logger.setLevel("INFO")

app = FastAPI(
    title="NetForensics Ingestion Gateway",
    description="Validates distributed sensor streams and publishes to Kafka message bus.",
    version="5.0.0"
)

security = HTTPBearer()

# Mocking JWT validation. In prod, this verifies RS256 token and extracts Org/Tenant ID.
async def verify_tenant(credentials: HTTPAuthorizationCredentials = Security(security)) -> str:
    """Extracts tenant_id from bearer token."""
    token = credentials.credentials
    if token == "invalid":
         raise HTTPException(status_code=401, detail="Invalid token")
    # In a real environment: jwt.decode(token, public_key) -> payload["tenant_id"]
    return "org_" + token[:6]  # Mock tenant ID


@app.on_event("startup")
async def startup_event():
    logger.info("Starting Ingestion Gateway.")
    try:
        await kafka_service.connect()
    except Exception as e:
        logger.error(f"Kafka connection failed during startup: {e}")
        # Not exiting right away -- retry logic handles transient unavailable brokers


@app.on_event("shutdown")
async def shutdown_event():
    logger.info("Shutting down Ingestion Gateway.")
    await kafka_service.disconnect()


async def process_batch(
    topic: str,
    tenant_id: str,
    req: IngestionRequest,
    model_class
) -> dict:
    start = time.time()
    
    # Generate common enterprise metadata envelope once per batch
    envelope = EnterpriseMetadata(
        tenant_id=tenant_id,
        sensor_id=req.sensor_id
    ).model_dump()
    
    valid_events = []
    
    for item in req.events:
        try:
            # Validate schema
            validated = model_class(**item).model_dump()
            # Merge with Enterprise Envelope
            validated.update(envelope)
            valid_events.append(validated)
        except ValidationError as e:
            logger.warning("Dropped invalid event: %s. Schema error: %s", item, e.errors())
    
    if valid_events:
        await kafka_service.publish_events(topic, tenant_id, valid_events)
    
    elapsed_ms = (time.time() - start) * 1000
    logger.info(
        "Processed batch topic=%s, ingested=%d, dropped=%d, time=%.2fms",
        topic, len(valid_events), len(req.events) - len(valid_events), elapsed_ms
    )
    
    return {
        "status": "published",
        "topic": topic,
        "processed": len(valid_events),
        "dropped": len(req.events) - len(valid_events)
    }


# ─── INGESTION ENDPOINTS ──────────────────────────────────────────────────────

@app.post("/api/v1/ingest/flows")
async def ingest_flows(
    request: IngestionRequest,
    tenant_id: str = Depends(verify_tenant)
) -> dict:
    """Accepts aggregated flow stats from sensors, streams to Kafka: nf.flows"""
    return await process_batch("nf.flows", tenant_id, request, FlowMetadata)


@app.post("/api/v1/ingest/packets")
async def ingest_packets(
    request: IngestionRequest,
    tenant_id: str = Depends(verify_tenant)
) -> dict:
    """Accepts L3/L4 packet metadata streams, streams to Kafka: nf.raw_packets"""
    return await process_batch("nf.raw_packets", tenant_id, request, RawPacketMetadata)


@app.post("/api/v1/ingest/tls")
async def ingest_tls(
    request: IngestionRequest,
    tenant_id: str = Depends(verify_tenant)
) -> dict:
    """Accepts extracted L7 TLS handshakes / JA3, streams to Kafka: nf.tls"""
    return await process_batch("nf.tls", tenant_id, request, TLSFingerprintEvent)


@app.post("/api/v1/ingest/alerts")
async def ingest_alerts(
    request: IngestionRequest,
    tenant_id: str = Depends(verify_tenant)
) -> dict:
    """Accepts alerts generated by out-of-band processing, streams to Kafka: nf.alerts"""
    return await process_batch("nf.alerts", tenant_id, request, AlertEvent)


@app.get("/health")
async def health_check():
    return {
        "status": "healthy",
        "kafka_connected": kafka_service._connected
    }
