from datetime import datetime, timezone
from typing import Optional, Dict, Any, List
from pydantic import BaseModel, ConfigDict, Field

# Base metadata that MUST be applied to all documents in the Enterprise Lake
class EnterpriseMetadata(BaseModel):
    tenant_id: str                      # For multi-tenancy logical isolation
    sensor_id: str                      # Identifies the physical/virtual capture node
    ingestion_timestamp: float = Field(
        default_factory=lambda: datetime.now(timezone.utc).timestamp()
    )                                   # Attached by this API Gateway
    schema_version: str = "v1.0"

class RawPacketMetadata(BaseModel):
    """Normalized packet metadata representing Layer 3/4 headers"""
    timestamp: float
    src_ip: str
    dst_ip: str
    src_port: Optional[int] = None
    dst_port: Optional[int] = None
    protocol: str                       # TCP, UDP, ICMP, etc.
    size: int
    tcp_flags: Optional[str] = None
    payload_entropy: Optional[float] = None

class FlowMetadata(BaseModel):
    """Aggregate conversational flow data (Zeek/NetFlow style)"""
    flow_id: str
    start_time: float
    end_time: float
    duration: float
    src_ip: str
    dst_ip: str
    src_port: int
    dst_port: int
    protocol: str
    packet_count: int
    bytes_transferred: int
    app_protocol: Optional[str] = None  # e.g., 'http', 'tls'
    state: Optional[str] = None         # Connection state (S0, SF, REJ)

class TLSFingerprintEvent(BaseModel):
    """TLS Layer 7 Event"""
    timestamp: float
    src_ip: str
    dst_ip: str
    tls_version: str
    sni: str
    ja3: Optional[str] = None           # Client fingerprint missing in TLS1.3
    ja3_string: Optional[str] = None
    ja3s: Optional[str] = None          # Server fingerprint
    cipher_suites: List[int] = Field(default_factory=list)

class AlertEvent(BaseModel):
    """Schema for alerts generated by the AI Engines (passed back into Kafka)"""
    alert_id: str
    engine_name: str                    # e.g., "AutonomousHunter", "FingerprintCorrelator"
    severity: str                       # CRITICAL, HIGH, MEDIUM, LOW
    title: str
    description: str
    mitre_tactics: List[str]            # e.g., ["Defense Evasion", "Command and Control"]
    mitre_techniques: List[str]         # e.g., ["T1071.001"]
    evidence: Dict[str, Any]
    affected_ips: List[str]

# Composition models used in API Requests
class IngestionRequest(BaseModel):
    sensor_id: str
    events: List[Dict[str, Any]]        # Raw opaque blobs that we will type check in the handler
